# This is a sample Dockerfile you can modify to deploy your own app based on face_recognition

FROM python:3.6


RUN apt-get -y update
RUN apt-get -y install wget unzip \
                       build-essential cmake git pkg-config libatlas-base-dev gfortran \
                       libjasper-dev libgtk2.0-dev libavcodec-dev libavformat-dev \
                       libswscale-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libv4l-dev libboost-all-dev 

RUN wget https://bootstrap.pypa.io/get-pip.py && python get-pip.py

RUN pip3 install numpy

RUN git clone https://github.com/davisking/dlib.git && \
    cd dlib && \
    mkdir build && \
    cd build && \
    cmake .. -DDLIB_USE_CUDA=0 -DUSE_AVX_INSTRUCTIONS=1 && \
    cmake --build . && \
    cd .. && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS --no DLIB_USE_CUDA && \
    cd && \
    pip install face_recognition && \
    pip install pyglet && \
    cd && \
RUN wget https://github.com/Itseez/opencv/archive/3.2.0.zip && unzip 3.2.0.zip \
    && mv opencv-3.2.0 /opencv

RUN mkdir /opencv/release
WORKDIR /opencv/release

RUN cmake -DBUILD_TIFF=ON \
        -DBUILD_opencv_java=OFF \
        -DWITH_CUDA=OFF \
        -DENABLE_AVX=ON \
        -DWITH_OPENGL=ON \
        -DWITH_OPENCL=ON \
        -DWITH_IPP=OFF \
        -DWITH_TBB=ON \
        -DWITH_EIGEN=ON \
        -DWITH_V4L=ON \
        -DWITH_VTK=OFF \
        -DBUILD_TESTS=OFF \
        -DBUILD_PERF_TESTS=OFF \
        -DCMAKE_BUILD_TYPE=RELEASE \
        -DBUILD_opencv_python2=OFF \
        -DCMAKE_INSTALL_PREFIX=$(python3.6 -c "import sys; print(sys.prefix)") \
        -DPYTHON3_EXECUTABLE=$(which python3.6) \
        -DPYTHON3_INCLUDE_DIR=$(python3.6 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") \
        -DPYTHON3_PACKAGES_PATH=$(python3.6 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") ..

RUN make -j4
RUN make install

CMD ["bash"]

RUN cd /usr/local/lib/python3.6/site-packages/ && \
    ls -l *.so && \
    cd /usr/local/lib/python3.6/site-packages/ && \
    mv cv2.cpython-36m-darwin.so cv2.so && \
    cd ~ && \
    cd ~/.virtualenvs/cv/lib/python3.6/site-packages/ && \
    ln -s /usr/local/lib/python3.6/site-packages/cv2.so cv2.so && \
    cd ~ && \
    git clone https://github.com/vduraphe/face_recognition.git && \
    cd face_recognition/examples/

CMD python3 facerec_from_webcam_faster.py
 